### ISSUE TITLE
Willow-Bootstrap installation in Pharo 9 broken (win 10)

### ISSUE THREAD

**Issue by sanjayminni** [ba-st/Willow-Bootstrap#114]
Willow-Bootstrap installation in Pharo 9 appears to be broken (Win 10 Pharo9.0.0 build: 1427, commit: d19ae7d, date: 21 May 2021)

![WillowBootstrapLoadingErr](https://user-images.githubusercontent.com/12030766/119156461-e02c4300-ba71-11eb-971c-a356297b9697.png)

**Comment by gcotelli** [comment]
Hi, this looks like a Pharo error, not Willow per se. Pharo 9 is still in beta so we're not using it in production, but I will try to test it on my machine.

**Comment by sanjayminni** [comment]
is working since so this issue can be closed
